telegram_token = "http://localhost:26657"
telegram_chat_id = ""
pypd_api_key = ""
pypd_service_key = ""
pypd_herf = ""
height_increasing_time_period = 10
missing_block_trigger = 10
free_disk_trigger = 10
node_config_dir = ""